### ISSUE TITLE
Cumulative Moderna goes from 30311 down to 23661 from 25th to 26th Jan

### ISSUE THREAD

**Issue by CorneliusvonLenthe** [mathiasbynens/covid-19-vaccinations-germany#9]
firstDosesCumulativeModerna[daten_stand = 2021-01-25] = 30311
firstDosesCumulativeModerna[daten_stand = 2021-01-26] = 23661

![image](https://user-images.githubusercontent.com/74565481/107118618-4eae1200-6882-11eb-88ed-ee30e21a8727.png)

Any idea?

**Comment by mathiasbynens** [comment]
The drop on 2021-01-26 is not an error in our scripts — it matches the data reported by the RKI, which overreported the numbers for 2021-01-25. More info: https://github.com/mathiasbynens/covid-19-vaccinations-germany/issues/6

Due to the same issue, there's a visible drop in the Bayern chart: https://mathiasbynens.github.io/covid-19-vaccinations-germany/#bayern

**Comment by mathiasbynens** [comment]
By the way, I'd love to hear more about how you're using the data. Let me know if you have a project I can link to.
